name: Spotless Check

on:
  pull_request:
    paths:
      - '**/*.kt'
  push:
    branches:
      - main
      - master
      - '**'

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Get changed files
        id: changed-files
        run: |
          git diff --name-only origin/${{ github.base_ref }}... > changed_files.txt

      - name: Run Spotless Check on changed files
        if: success()
        run: |
          CHANGED_FILES=$(grep ".kt" changed_files.txt | tr '\n' ' ')
          if [ -n "$CHANGED_FILES" ]; then
            ./gradlew spotlessCheck --files $CHANGED_FILES
          else
            echo "No Kotlin files changed."
          fi
