name: Backend Tests and Formatting

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Spotless Check on changed files
        working-directory: calculator-backend
        if: success()
        run: |
          git diff --name-only > changed_files.txt
          CHANGED_FILES=$(grep ".kt$" changed_files.txt | tr '\n' ' ' | sed "s/calculator-backend\///g")
          if [ -n "$CHANGED_FILES" ]; then
            ./gradlew spotlessCheck --files $CHANGED_FILES
          else
            echo "No Kotlin files changed."
          fi

  run-backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        working-directory: calculator-backend
        run: chmod +x gradlew

      - name: Run Backend Tests
        working-directory: calculator-backend
        run: ./gradlew test



